{"name": "test_post_create_token", "status": "broken", "statusDetails": {"message": "NameError: name 'user_cred' is not defined", "trace": "def test_post_create_token():\n        file_path = \"/Users/abijithmg/PycharmProjects/PyAPIAutomation/tests/Data_driven_testing/testdata_ddt.xlsx\"\n        credentials = read_credentials_from_excel(file_path)\n    \n        for cuser_cred in credentials:\n>           username = user_cred[\"username\"]\nE           NameError: name 'user_cred' is not defined\n\ntests/Data_driven_testing/test_ddt.py:41: NameError"}, "start": 1706516990806, "stop": 1706516990809, "uuid": "09779c1f-cfee-420a-b5c5-88cd8471d074", "historyId": "a18d6b414cfa85182578961059e76dc7", "testCaseId": "a18d6b414cfa85182578961059e76dc7", "fullName": "tests.Data_driven_testing.test_ddt#test_post_create_token", "labels": [{"name": "parentSuite", "value": "tests.Data_driven_testing"}, {"name": "suite", "value": "test_ddt"}, {"name": "host", "value": "PlayOsmos-MacBook-Pro.local"}, {"name": "thread", "value": "71495-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Data_driven_testing.test_ddt"}]}